other test

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -38,6 +38,17 @@ jobs:
     needs: [build-pipeline]
     runs-on: ubuntu-24.04
 
+    services:
+      mysql:
+        image: mysql:8.0
+
+        env:
+          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
+          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
+
+        ports:
+          - 3306:3306
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v5
@@ -55,9 +66,43 @@ jobs:
       - name: Build
         run: dotnet build ./ProyectoApi.slnx --no-restore --configuration Release
 
+      - name: Wait for MySQL
+        env:
+          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
+
+        run: |
+          echo "Esperando a que MySQL esté disponible..."
+
+          for i in {1..30}; do
+
+            if docker run --rm \
+              --network host \
+              mysql:8.0 \
+              mysqladmin ping \
+              -h 127.0.0.1 \
+              -P 3306 \
+              -u root \
+              -p"${MYSQL_ROOT_PASSWORD}" \
+              --silent; then
+
+              echo "MySQL está listo."
+              exit 0
+            fi
+
+            echo "Intento $i/30 - MySQL todavía no está disponible."
+            sleep 2
+
+          done
+
+          echo "ERROR: MySQL no estuvo disponible."
+
+          docker ps -a
+
+          exit 1
+
       - name: Test database connection
         env:
-          ConnectionStrings__DefaultConnection: "Server=${{ secrets.MYSQL_SERVER }};Port=${{ secrets.MYSQL_PORT }};Database=${{ secrets.MYSQL_DATABASE }};User=${{ secrets.MYSQL_USER }};Password=${{ secrets.MYSQL_PASSWORD }};"
+          ConnectionStrings__DefaultConnection: "Server=127.0.0.1;Port=3306;Database=${{ secrets.MYSQL_DATABASE }};User=root;Password=${{ secrets.MYSQL_ROOT_PASSWORD }};"
 
         run: |
           output=$(dotnet test ./ProyectoApi.slnx \
@@ -76,6 +121,9 @@ jobs:
             exit 1
           fi
 
+      # ========================================================
+      # MYSQL LOGS SI FALLA
+      # ========================================================
       - name: MySQL logs
         if: failure()
         run: |
