add log function

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -50,12 +50,6 @@ jobs:
         ports:
           - 3306:3306
 
-        options: >-
-          --health-cmd="mysqladmin ping -h 127.0.0.1"
-          --health-interval=10s
-          --health-timeout=5s
-          --health-retries=10
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v5
@@ -72,6 +66,40 @@ jobs:
 
       - name: Build
         run: dotnet build ./ProyectoApi.slnx --no-restore --configuration Release
+
+      - name: Wait for MySQL
+        env:
+          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
+
+        run: |
+          echo "Esperando a que MySQL esté disponible..."
+
+          for i in {1..30}; do
+
+            if docker run --rm \
+              --network host \
+              mysql:8.0 \
+              mysqladmin ping \
+              -h 127.0.0.1 \
+              -P 3306 \
+              -u root \
+              -p"${MYSQL_ROOT_PASSWORD}" \
+              --silent; then
+
+              echo "MySQL está listo."
+              exit 0
+            fi
+
+            echo "Intento $i/30 - MySQL todavía no está disponible."
+            sleep 2
+
+          done
+
+          echo "ERROR: MySQL no estuvo disponible."
+
+          docker ps -a
+
+          exit 1
 
       - name: Test database connection
         env:
@@ -93,3 +121,19 @@ jobs:
             echo "ERROR: No se encontró ningún test con el filtro especificado."
             exit 1
           fi
+
+      - name: MySQL logs
+        if: failure()
+        run: |
+          echo "======================================"
+          echo "DOCKER CONTAINERS"
+          echo "======================================"
+
+          docker ps -a
+
+          echo "======================================"
+          echo "MYSQL LOGS"
+          echo "======================================"
+
+          docker ps -aq --filter "ancestor=mysql:8.0" | \
+            xargs -r docker logs
